version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      day: monday
    ignore:
      - dependency-name: "@types/vscode"
    groups:
      all:
        patterns:
          - "*"
        # Do not update to Chai v5 because it cannot be used from vscode
        exclude-patterns:
          - "chai"
          - "@types/chai"
